import { NextRequest, NextResponse } from "next/server";

export const maxDuration = 30;

interface EmailPayload {
  resendApiKey: string;
  recipients: string[];
  date: string;
  duration: string;
  youSpoke: string;
  otherSpoke: string;
  summary: string;
  transcript: string;
}

function markdownToHtml(md: string): string {
  return md
    // Headers
    .replace(/^## (.+)$/gm, '<h2 style="color:#6366f1;font-size:18px;margin:24px 0 12px 0;padding-bottom:6px;border-bottom:1px solid #e5e7eb;">$1</h2>')
    // Bold
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    // Checkboxes
    .replace(/^- \[ \] (.+)$/gm, '<div style="margin:4px 0;padding-left:8px;">&#9744; $1</div>')
    .replace(/^- \[x\] (.+)$/gm, '<div style="margin:4px 0;padding-left:8px;">&#9745; $1</div>')
    // Bullet points
    .replace(/^- (.+)$/gm, '<div style="margin:4px 0;padding-left:8px;">&bull; $1</div>')
    // Line breaks
    .replace(/\n\n/g, '<br/>')
    .replace(/\n/g, '');
}

export async function POST(request: NextRequest) {
  try {
    const body: EmailPayload = await request.json();
    const { resendApiKey, recipients, date, duration, youSpoke, otherSpoke, summary, transcript } = body;

    if (!resendApiKey) {
      return NextResponse.json({ error: "Resend API key is required" }, { status: 400 });
    }
    if (!recipients || recipients.length === 0) {
      return NextResponse.json({ error: "At least one email recipient is required" }, { status: 400 });
    }

    const summaryHtml = markdownToHtml(summary);

    const truncatedTranscript = transcript.length > 20000
      ? transcript.substring(0, 20000) + "\n\n... (transcript truncated for email)"
      : transcript;

    const htmlBody = `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;color:#1a1a1a;max-width:680px;margin:0 auto;padding:20px;background:#f9fafb;">
  <div style="background:white;border-radius:12px;border:1px solid #e5e7eb;overflow:hidden;">
    <!-- Header -->
    <div style="background:linear-gradient(135deg,#6366f1,#8b5cf6);padding:28px 24px;color:white;">
      <h1 style="margin:0;font-size:22px;font-weight:700;">Meeting Summary</h1>
      <p style="margin:6px 0 0;opacity:0.9;font-size:14px;">${date}</p>
    </div>

    <!-- Stats -->
    <div style="display:flex;border-bottom:1px solid #e5e7eb;">
      <div style="flex:1;padding:16px;text-align:center;border-right:1px solid #e5e7eb;">
        <div style="font-size:20px;font-weight:700;color:#1a1a1a;">${duration}</div>
        <div style="font-size:12px;color:#6b7280;">Duration</div>
      </div>
      <div style="flex:1;padding:16px;text-align:center;border-right:1px solid #e5e7eb;">
        <div style="font-size:20px;font-weight:700;color:#22c55e;">${youSpoke}</div>
        <div style="font-size:12px;color:#6b7280;">You spoke</div>
      </div>
      <div style="flex:1;padding:16px;text-align:center;">
        <div style="font-size:20px;font-weight:700;color:#6366f1;">${otherSpoke}</div>
        <div style="font-size:12px;color:#6b7280;">Other spoke</div>
      </div>
    </div>

    <!-- Summary -->
    <div style="padding:24px;">
      ${summaryHtml}
    </div>

    <!-- Transcript -->
    <div style="padding:0 24px 24px;">
      <details>
        <summary style="cursor:pointer;font-size:14px;font-weight:600;color:#6366f1;padding:8px 0;">
          View Full Transcript
        </summary>
        <pre style="background:#f3f4f6;border-radius:8px;padding:16px;font-size:11px;line-height:1.6;white-space:pre-wrap;word-wrap:break-word;max-height:400px;overflow-y:auto;margin-top:8px;">${truncatedTranscript.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</pre>
      </details>
    </div>

    <!-- Footer -->
    <div style="background:#f9fafb;padding:16px 24px;text-align:center;border-top:1px solid #e5e7eb;">
      <p style="margin:0;font-size:11px;color:#9ca3af;">
        Generated by Meeting Transcriber &bull; AI-powered meeting notes
      </p>
    </div>
  </div>
</body>
</html>`;

    const response = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${resendApiKey}`,
      },
      body: JSON.stringify({
        from: "Meeting Transcriber <onboarding@resend.dev>",
        to: recipients,
        subject: `Meeting Summary — ${date}`,
        html: htmlBody,
      }),
    });

    if (!response.ok) {
      const error = await response.text();
      return NextResponse.json(
        { error: `Email send failed: ${error}` },
        { status: response.status }
      );
    }

    const result = await response.json();
    return NextResponse.json({ success: true, id: result.id });
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : "Unknown error";
    return NextResponse.json({ error: `Email error: ${message}` }, { status: 500 });
  }
}
